import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

//components
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import Footer from "@/components/Footer";

const JetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono"
});

export const metadata = {
  title: "Muhammad Huzaifa Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body
          className={`${JetBrainsMono.variable} min-h-screen flex flex-col`}
        >
          <Header />
          <StairTransition />
          <main className="flex-1">
          <PageTransition>
          {children}
          </PageTransition>
          </main>
          <Footer />
      </body>
    </html>
  );
}
